# 07 - NumPy: broadcasting, vectorización y rendimiento

Objetivos:

- Comprender **broadcasting** en operaciones entre arrays de distintas formas.
- Reemplazar bucles por **vectorización** para ganar rendimiento.
- Usar **linalg** (álgebra lineal) para operaciones comunes.
- Medir tiempos con `%%timeit` (en Jupyter) o `timeit` en código.


## 1. Broadcasting: reglas y ejemplos

In [1]:
import numpy as np

x = np.array([[1,2,3],[4,5,6]])
b = np.array([10, 20, 30])       # Se 'expande' por filas
print(x + b)

c = np.array([[100],[200]])      # Se 'expande' por columnas
print(x + c)

[[11 22 33]
 [14 25 36]]
[[101 102 103]
 [204 205 206]]


## 2. Vectorización vs bucles (benchmark simple)

In [2]:
import numpy as np, time

n = 2_000_00  # 200k elementos
a = np.random.rand(n)
b = np.random.rand(n)

# Suma con bucle (no vectorizado)
t0 = time.time()
c_loop = np.empty_like(a)
for i in range(n):
    c_loop[i] = a[i] + b[i]
t1 = time.time()

# Vectorizado
t2 = time.time()
c_vec = a + b
t3 = time.time()

print(f"Bucle:     {t1 - t0:.4f} s")
print(f"Vectorizado:{t3 - t2:.4f} s")
print("¿Resultados iguales?", np.allclose(c_loop, c_vec))

Bucle:     0.0435 s
Vectorizado:0.0000 s
¿Resultados iguales? True


## 3. Álgebra lineal con `numpy.linalg`

In [ ]:
M = np.array([[3., 2.], [1., 4.]])
b = np.array([10., 12.])

# Resolver Mx = b
x = np.linalg.solve(M, b)
print("Solución x:", x)

# Autovalores y autovectores
w, v = np.linalg.eig(M)
print("Autovalores:", w)
print("Autovectores:\n", v)

## 4. Pequeña visualización (sin estilos)

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

x = np.linspace(0, 2*np.pi, 200)
y = np.sin(x)

plt.figure()
plt.plot(x, y)
plt.title("Seno vectorizado con NumPy")
plt.xlabel("x")
plt.ylabel("sin(x)")
plt.show()

## 📝 Ejercicios

1) Dado un array 2x3 y un vector de longitud 3, realiza una suma con broadcasting y explica la forma resultante.  
2) Genera dos arrays grandes y compara el tiempo de `a*b + a` hecho con bucles vs vectorizado.  
3) Resuelve un sistema lineal 3x3 cualquiera con `np.linalg.solve` y verifica el resultado.


## 📝 Respuestas

In [5]:
import numpy as np

A = np.array([[1,2,3],
             [4,5,6]])

B = np.array([10,20,30])